language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"

before_install:
  - openssl aes-256-cbc -K $encrypted_25555bb76dbd_key -iv $encrypted_25555bb76dbd_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
     export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
     curl https://sdk.cloud.google.com | bash;
    fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - tar -xzf credentials.tar.gz
  - mkdir -p lib
  - gcloud auth activate-service-account --key-file client-secret.json
  - gcloud config set project 'global-ember-meetup-frontend'
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version


after_success:
  - test $TRAVIS_BRANCH = "master" && npm deploy

install:
  - npm install
  - bower install

script:
  - npm test
