language: node_js
node_js:
- "6.7.0"
sudo: false
cache:
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - openssl aes-256-cbc -K $encrypted_25555bb76dbd_key -iv $encrypted_25555bb76dbd_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - export GOOGLE_APPLICATION_CREDENTIALS=client-secret.json
  - export GCLOUD_PROJECT=global-ember-meetup-frontend
  - gcloud version
  - tar -xzf credentials.tar.gz
  - mkdir -p lib
  - gcloud auth activate-service-account --key-file client-secret.json
  - gcloud config set project 'global-ember-meetup-frontend'
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

after_success:
  - ls -l
  - npm run deploy

install:
  - npm install
  - bower install

script:
  - npm test
